export function getGrid () {
    var grid = [
        {
            qty:500,
            ppp:.74,
        },
        {
            qty:1000,
            ppp:.64,
        },
        {
            qty:1500,
            ppp:.59,
        },
        {
            qty:2000,
            ppp:.53,
        },
        {
            qty:5000,
            ppp:.39,
        },
        {
            qty:10000,
            ppp:.32,
        },
        {
            qty:15000,
            ppp:.31,
        },
        {
            qty:20000,
            ppp:.30,
        },
        {
            qty:25000,
            ppp:.29,
        },
        {
            qty:50000,
            ppp:.28,
        },
        {
            qty:100000,
            ppp:.27,
        },
        {
            qty:250000,
            ppp:.26,
        },
        {
            qty:300000,
            ppp:.26,
        },
    ];

    return grid;

}
